### ISSUE TITLE
Error on Windows when using signal

### ISSUE THREAD

**Issue by budarin** [atassis/run-script-webpack-plugin#15]
Config:

```js
module.exports = {
    name: 'dev',
    watch: true,
    cache: { type: 'filesystem' },
    target: 'node',
    profile: false,
    mode: 'development',
    devtool: 'inline-source-map',
    entry: [path.resolve('./src/index.ts')],
    experiments: {
        topLevelAwait: true,
    },
    hot: true,
    output: {
        path: path.resolve('./dist'),
        filename: 'server.js',
        chunkFilename: '[name].js',
        libraryTarget: 'commonjs2',
        compareBeforeEmit: true,
    },
    resolve: {
        extensions: ['.ts', '.js', '.json'],
        modules: ['node_modules', 'src'],
        alias: {},
    },
    externals: [
        nodeExternals({
            allowlist: ['webpack/hot/poll?1000'],
        }),
    ],
    plugins: [
            new RunScriptWebpackPlugin({
            name: 'server.js',
            signal: true,
        }),
    ],
};
```

Error:
```
node:internal/process/per_thread:215
        throw new ERR_UNKNOWN_SIGNAL(sig);
        ^

TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: SIGUSR2
    at new NodeError (node:internal/errors:372:5)
    at process.kill (node:internal/process/per_thread:215:15)
    at RunScriptWebpackPlugin.afterEmit (D:\Projects\raketa\node_modules\run-script-webpack-plugin\dist\index.js:19:29)
    at Hook.eval [as callAsync] (eval at create (D:\Projects\raketa\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:17:1)
    at D:\Projects\raketa\node_modules\webpack\lib\Compiler.js:882:27
    at D:\Projects\raketa\node_modules\neo-async\async.js:2818:7
    at done (D:\Projects\raketa\node_modules\neo-async\async.js:3522:9)
    at writeOut (D:\Projects\raketa\rnode_modules\webpack\lib\Compiler.js:834:17)
    at D:\Projects\raketa\node_modules\webpack\lib\Compiler.js:869:7
    at arrayIterator (D:\Projects\raketa\node_modules\neo-async\async.js:3467:9) {
  code: 'ERR_UNKNOWN_SIGNAL'
}
```

Windows: 10
Node.js v18.0.0
Webpack: 5

Keyboard option also does not work (

the server does not always restart after reassembly on MacOs

**Comment by atassis** [comment]
There is no `SIGUSR2` signal in windows, as I understand. Have to check how this thing should work in windows, but you can apply a string value to a signal instead, though you have to find out which is correct for HMR (or for your tool) to use

**Comment by budarin** [comment]
> but you can apply a string value to a signal instead, though you have to find out which is correct for HMR (or for your tool) to use

Ok

it is also necessary to give access to the time settings for monitoring updates - almost all the time changes and reassembly occur, but there is no server restart

**Comment by atassis** [comment]
Напиши по-русски плез, что имел ввиду, не понял последнюю просьбу)

**Comment by budarin** [comment]
При изменениях в коде происходит пересборка кода, но что-то лагает и не происходит перезапуск dev-servera
Вот  так выглядит нормальный запуск

![image](https://user-images.githubusercontent.com/8055157/166976350-de998aff-f7fd-49e9-ac1a-3dd672419b39.png)

А вот так когда лагает после пересборки

![image](https://user-images.githubusercontent.com/8055157/166976450-1c8ae623-9dbb-48c1-bfaf-999bb3ee7185.png)

Заметил, что такая ситуация возникает в большинстве своем если нажимать Ctrl+S в коде
Если просто покинуть окно редактора, то сохранение происходят спустя время и как правило на медленной Windows сервер успевает и пересобраться и перезапуститься

На маке практически всегда после пересборки сервер не перезапускается

Подозреваю что нужно тюнить параметры watch (делать его больше и троттлить)

**Comment by atassis** [comment]
А можешь тестовую репку создать и поделиться ей?
Я давно не работал с проектами, для которых плагин запилил, да и мб и не отловлю на них

**Comment by budarin** [comment]
Да, сделаю проект и маякну

**Comment by budarin** [comment]
Вот тестовый [проект](https://github.com/budarin/simple-project)

**Comment by atassis** [comment]
Правильно ли я понимаю, что проект перезапускается только каждое второе обновление?

**Comment by budarin** [comment]
На Windows у меня - практически да, на маке практически не перезапускается - редко когда проскакивает перезапуск

**Comment by atassis** [comment]
Выкатил 0.0.12 версию, проверяй)

**Comment by budarin** [comment]
в новой версии 
```
.../node_modules/webpack/lib/logging/Logger.js:123
                        throw new Error(`No such label '${label}' for WebpackLogger.timeEnd()`);
                        ^

Error: No such label 'emitAssets' for WebpackLogger.timeEnd()
    at WebpackLogger.timeEnd (.../node_modules/webpack/lib/logging/Logger.js:123:10)
    at .../node_modules/webpack/lib/Watching.js:182:15
    at .../node_modules/webpack/lib/Compiler.js:885:14
    at eval (eval at create (.../node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at WebpackDeadcodePlugin.handleAfterEmit (.../node_modules/webpack-deadcode-plugin/src/index.js:32:3)
    at _next0 (eval at create (.../node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (.../node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at .../node_modules/run-script-webpack-plugin/dist/index.js:52:17
    at Timeout._onTimeout (.../node_modules/run-script-webpack-plugin/dist/index.js:93:26)
    at listOnTimeout (node:internal/timers:564:17)
```

**Comment by budarin** [comment]
тут есть кто-нибудь? :)

**Comment by atassis** [comment]
Есть,  я просто не успеваю:(
Я помню,  но сил пока нет,  резко в жизни все "весело" стало
Я внёс баг в итоге и это чекать нужно

**Comment by budarin** [comment]
понял, спасибо!

**Comment by budarin** [comment]
Привет!
лучше не стало?)

**Comment by atassis** [comment]
Задеплоил версию 0.1.0
Отпишись по результатам

**Comment by budarin** [comment]
Все отлично!
Спасибо!
