### ISSUE TITLE
Error: No such label 'emitAssets' for WebpackLogger.timeEnd()

### ISSUE THREAD

**Issue by ZeroCho** [atassis/run-script-webpack-plugin#16]
When following nest.js doc for hot reloading,
[Hot reloading docs](https://docs.nestjs.com/recipes/hot-reload)

```
Error: No such label 'emitAssets' for WebpackLogger.timeEnd()
\Desktop\projects\github_visualization\backend\node_modules\webpack\lib\logging\Logger.js:123
                        throw new Error(`No such label '${label}' for WebpackLogger.timeEnd()`);
```
this error happens.
It works well with @0.0.11 but @0.0.12 causes this error.

When looking for [the commit](https://github.com/atassis/run-script-webpack-plugin/commit/1e9ba4b26c7f0117d7ae95f06d21ffe266febef2) which has changes between @0.0.11 and @0.0.12, I could only find `this.worker.pid`, but I'm not sure this causes the error.

**Comment by atassis** [comment]
Reverted the breaking changes. version `0.0.14` deployed. Apologies for a late revert :eyes:

**Comment by atassis** [comment]
Test it if it works and then i'll close an issue. Have no projects to test by myself for now

**Comment by ZeroCho** [comment]
Okay, I'll test 0.0.14 and let you know. Thank you.

**Comment by ZeroCho** [comment]
It works well with @0.0.14!
